### PR TITLE
Feature/#22-Mobile-Nav

### LINKED ISSUE #22: Mobile: nav

### PR DESCRIPTION
**Pull request by dutraneto**
Stretch nav on mobile

### CODE REVIEW

**Comment by dutraneto** [comment]
@marceloglacial, #22 for review

**Comment by marceloglacial** [comment]
Please follow the design. 
Needs more space on the left.

Screen Shot 2021-03-03 at 8 15 36 AM

Screen Shot 2021-03-03 at 8 21 46 AM

**Review by marceloglacial — CHANGES_REQUESTED** [review]
Read the comments

**Comment by dutraneto** [comment]
I'll take a closer looking

**Comment by dutraneto** [comment]
image

**Comment by dutraneto** [comment]
@marceloglacial, #22 ready for review

**Review by marceloglacial — APPROVED** [review]
Still having issues https://1drv.ms/v/s!AiNBHZuhouESlf5F8AkJpRj0b4DjHA?e=adIDTM

**Review by marceloglacial — CHANGES_REQUESTED** [review]
Still having issues https://1drv.ms/v/s!AiNBHZuhouESlf5F8AkJpRj0b4DjHA?e=adIDTM

**Comment by dutraneto** [comment]
> Still having issues https://1drv.ms/v/s!AiNBHZuhouESlf5F8AkJpRj0b4DjHA?e=adIDTM

Are those tests coming from chrome?
I've noticed the same issues coming from chrome only if you zoom it out, but you can also find that the navbar's font-sizes are not as the same size they were set to, which is kinda weird and I don't think that issue comes from code, but from the browser.
I've tested on Safari too and it seems to work well.
I've also tested it on my phone and it did not show that kind of problem whatsoever.

**What kind of tool would most recommend for these tests?**

**Comment by dutraneto** [comment]
https://drive.google.com/file/d/1qkD0au01xyiP_pFB7hzycc4TX8Arj9Iu/view?usp=sharing

Chrome

**Comment by dutraneto** [comment]
https://drive.google.com/file/d/17pkzh-UQC5p04r3f2AT_HdxJxyO0gOcw/view?usp=sharing

Safari

**Comment by dutraneto** [comment]
https://drive.google.com/file/d/18iOW_AQFWXYtf3OyttfpdoYiJZcGZ-I-/view?usp=sharing

Firefox

**Comment by dutraneto** [comment]
https://drive.google.com/file/d/1aJv4AfGmvoMynNjhOAxh7Cz4EnxtfMsp/view?usp=sharing

IphoneXR

**Comment by dutraneto** [comment]
I'll keep testing anyways. Thank you for reviewing

**Comment by marceloglacial** [comment]
@dutraneto If you remove the main component, it's working. Try to test the nav without it. 

Please, fix it on iPad portrait (should be the same styles of mobile) and keep it as is on portrait (like desktop)

Thank you.

Screen Shot 2021-03-03 at 11 02 12 PM

**Comment by dutraneto** [comment]
> @dutraneto If you remove the main component, it's working. Try to test the nav without it.
> 
> Please, fix it on iPad portrait (should be the same styles of mobile) and keep it as is on portrait (like desktop)
> 
> Thank you.
> 
> Screen Shot 2021-03-03 at 11 02 12 PM

I'll do it!

**Comment by dutraneto** [comment]
@marceloglacial, portrait mode navbar set for tablet resolutions. Please, review it.

**Comment by marceloglacial** [comment]
> @marceloglacial, portrait mode navbar set for tablet resolutions. Please, review it.

Good job! Thank you!

**Review by marceloglacial — APPROVED** [review]

**Pull request merged**
