### PR TITLE
Feature/23 mobile header

### PR DESCRIPTION
**Pull request by dutraneto**
@marceloglacial, this #23 is ready for review.

### CODE REVIEW

**Review by marceloglacial — CHANGES_REQUESTED** [review]
Move the shadow to the header instead the logo+social to avoid two shadows
Screen Shot 2021-03-04 at 12 34 22 PM

**Comment by marceloglacial** [comment]
Try to keep the logo aligned left and with the same padding space. If the screen is smaller, make the logo smaller.

Screen Shot 2021-03-04 at 12 33 57 PM
Screen Shot 2021-03-04 at 12 34 10 PM

**Comment by marceloglacial** [comment]
Try to keep the logo aligned left with the same padding space. 
Keep social at right 

Screen Shot 2021-03-04 at 12 34 30 PM

**Comment by dutraneto** [comment]
> Try to keep the logo aligned left with the same padding space.
> Keep social at right
> 
> Screen Shot 2021-03-04 at 12 34 30 PM

Done!

**Comment by dutraneto** [comment]
@marceloglacial, #23 changes are ready for review

**Review by marceloglacial — APPROVED** [review]

**Comment by marceloglacial** [comment]
Good job! Approved!

**Comment by dutraneto** [comment]
Awesome!

**Pull request merged**
